version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    env_file: mariadb_conf.env
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - moodle_nw
  moodle:
    image: 'bitnami/moodle:3'
    env_file: moodle_conf.env
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - moodle_nw
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
networks:
  moodle_nw:
